language: python
cache: pip
python:
- 3.7.8
- '3.8'
- '3.9'
group: dev
install:
- pip install -r tests/requirements.txt
- cp packaging/setup.py .
- pip install .
env:
- PYTHONPATH=.
script:
- python -Werror tests/smoke_test.py
- python -m unittest discover tests
- echo test
jobs:
  include:
  - name: Python 3.11
    dist: jammy
    python: '3.11'
    before_install:
    - pip install --upgrade pip
    - pip install wheel==0.41.2
    - pip install setuptools==65.5.0
